name: CDN
on:
  push:
    branches:
    - master

jobs:
  upload:
    name: Upload to Azure Blob Storage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Extract Package Version
        uses: Saionaro/extract-package-version@v1.1.1
        with:
          path: html
        id: pkg

      - name: Install Dependencies
        run: |
          npm install
          npm run bootstrap

      - name: Bundle
        run: npm run bundle
        working-directory: html

      - name: Upload Assets
        uses: runlyio/azure-versioned-storage@v2
        with:
          sourceDir: html/dist
          version: v${{ steps.pkg.outputs.version }}
          container: runlyjs
          connectionString: ${{ secrets.AZURE_STORAGE }}
