name: CDN
on:
  push:
    branches:
    - master

jobs:
  upload:
    name: Upload to Azure Blob Storage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - uses: runlyio/extract-package-version@configure-path
        with:
          path: cdn
        id: pkg

      - name: Install Dependencies
        run: |
          npm install
          npm run bootstrap

      - name: Bundle
        run: npm run bundle
        working-directory: cdn

      - uses: runlyio/azure-versioned-storage@v1
        with:
          sourceDir: cdn/dist
          version: v${{ steps.pkg.outputs.version }}
          container: runlyjs
          storageSasUrl: ${{ secrets.STORAGE_SAS_URL }}
